package app

import (
	"encoding/json"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	imgproc "immich-go/internal/image"
	"immich-go/internal/ml"
	"immich-go/internal/video"
)

// jobState tracks the progress of a running (or finished) job queue. Immich
// reports counts as {active, completed, failed, delayed} but this scaffold
// only needs active/total to drive a progress bar, so we keep the full shape
// for compatibility and fill active/completed.
type jobState struct {
	forceChain bool
	mu         sync.Mutex
	active     int
	total      int
	completed  int
	failed     int
	running    bool
	startedAt  time.Time
	finishedAt time.Time
	lastError  string
}

func (s *jobState) begin(total int) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.total = total
	s.active = total
	s.completed = 0
	s.failed = 0
	s.running = true
	s.startedAt = time.Now()
	s.lastError = ""
}

func (s *jobState) tick(ok bool, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.active--
	s.completed++
	if !ok {
		s.failed++
		if err != nil {
			s.lastError = err.Error()
		}
	}
	if s.active <= 0 {
		s.running = false
		s.finishedAt = time.Now()
	}
}

func (s *jobState) snapshot() gin.H {
	s.mu.Lock()
	defer s.mu.Unlock()
	return gin.H{
		"active":    s.active,
		"completed": s.completed,
		"failed":    s.failed,
		"delayed":   0,
		"total":     s.total,
		"running":   s.running,
		"startedAt": s.startedAt.UTC().Format(time.RFC3339),
		"finishedAt": func() string {
			if s.finishedAt.IsZero() {
				return ""
			}
			return s.finishedAt.UTC().Format(time.RFC3339)
		}(),
		"lastError": s.lastError,
	}
}

// jobSpec describes the work for a single job id.
type jobSpec struct {
	// supported marks jobs this server can actually run. AI jobs (object /
	// facial / smart search) are reported for compatibility but not executed.
	supported bool
	// items returns the set of assets (ids + on-disk paths) the job should
	// process. Returning an empty slice means "nothing to do" (a no-op success).
	// force mirrors the official JobCreateDto.force: when true the job must
	// re-process ALL eligible assets, not only the ones missing byproducts.
	items func(a *App, force bool) ([]jobItem, error)
	// run processes one item. ok=false marks the item failed (counted but not
	// fatal — the job continues with the next item).
	run func(a *App, it jobItem) (ok bool, err error)
}

type jobItem struct {
	ID   string
	Path string
	Type string // IMAGE | VIDEO
}

// familyOfItem resolves the cache format family for a job item by sniffing its
// original bytes (cheap magic check; falls back to extension).
func familyOfItem(it jobItem) string {
	if raw, err := os.ReadFile(it.Path); err == nil {
		if f := imgproc.SniffFormat(raw); f != "" {
			return f
		}
	}
	switch strings.ToLower(filepath.Ext(it.Path)) {
	case ".jpg", ".jpeg":
		return "jpeg"
	case ".png":
		return "png"
	case ".heic", ".heif", ".avif":
		return "heic"
	case ".webp":
		return "webp"
	case ".gif":
		return "gif"
	default:
		return ""
	}
}

// jobRegistry maps immich job ids to their implementation. Jobs not listed
// here are unknown and rejected with 400.
func (a *App) jobRegistry() map[string]jobSpec {
	return map[string]jobSpec{
		"thumbnailGeneration": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				var assets []Asset
				q := a.store.DB.Where("is_trash = ?", false)
				if !force {
					// Missing OR stale (generated by an older pipeline version
					// for its format family — Epic S8). Legacy rows with no
					// family recorded are only stale once that family's
					// version has been bumped past 1.
					q = q.Where(
						"has_thumbnail = 0 OR (preview_family != '' AND thumb_version > 0 AND "+
							"thumb_version < (CASE preview_family "+
							"WHEN 'jpeg' THEN ? WHEN 'png' THEN ? WHEN 'heic' THEN ? "+
							"WHEN 'webp' THEN ? WHEN 'gif' THEN ? ELSE 9223372036854775807 END))",
						imgproc.CurrentCacheVersion(imgproc.FamilyJPEG),
						imgproc.CurrentCacheVersion(imgproc.FamilyPNG),
						imgproc.CurrentCacheVersion(imgproc.FamilyHEIC),
						imgproc.CurrentCacheVersion(imgproc.FamilyWebP),
						imgproc.CurrentCacheVersion(imgproc.FamilyGIF))
				}
				if err := q.Find(&assets).Error; err != nil {
					return nil, err
				}
				out := make([]jobItem, 0, len(assets))
				for _, x := range assets {
					out = append(out, jobItem{ID: x.ID, Path: x.OriginalPath, Type: x.Type})
				}
				return out, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				if _, err := os.Stat(it.Path); err != nil {
					return false, err
				}
				res, err := a.processMedia(it.Path, it.ID, "", it.Type, time.Time{})
				if err != nil {
					return false, err
				}
				thumbPath := ""
				if res.thumbBytes != nil {
					thumbPath = filepath.Join(a.cfg.ResourceDir, "thumbnail", it.ID+".jpg")
				}
				upd := map[string]any{
					"has_thumbnail": thumbPath != "", "resize_path": thumbPath,
					"thumb_version": imgproc.CurrentCacheVersion(imgproc.CacheFamily(familyOfItem(it))),
					"preview_family": familyOfItem(it),
					"preview_ver":   imgproc.CurrentCacheVersion(imgproc.CacheFamily(familyOfItem(it))),
					"updated_at":    time.Now().UTC(),
				}
				if err := a.store.DB.Model(&Asset{}).Where("id = ?", it.ID).Updates(upd).Error; err != nil {
					return false, err
				}
				return thumbPath != "", nil
			},
		},
		"metadataExtraction": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				// assets without an exif row, or with an empty exif row.
				var assets []Asset
				q := a.store.DB.Where("type = ? AND is_trash = ?", "IMAGE", false)
				if !force {
					q = q.Where("exif_id = ?", "")
				}
				if err := q.Find(&assets).Error; err != nil {
					return nil, err
				}
				out := make([]jobItem, 0, len(assets))
				for _, x := range assets {
					out = append(out, jobItem{ID: x.ID, Path: x.OriginalPath, Type: x.Type})
				}
				return out, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				if it.Type != "IMAGE" {
					return true, nil // only images carry EXIF in the scaffold
				}
				if _, err := os.Stat(it.Path); err != nil {
					return false, err
				}
				res, err := a.processMedia(it.Path, it.ID, "", it.Type, time.Time{})
				if err != nil {
					return false, err
				}
				// Backfill pixel dimensions/thumbhash now that decoding may
				// have gained new format support (e.g. HEIC).
				if res.width > 0 && res.height > 0 {
					a.store.DB.Model(&Asset{}).Where("id = ?", it.ID).Updates(map[string]any{
						"width": res.width, "height": res.height, "thumbhash": res.thumbhash, "updated_at": time.Now().UTC(),
					})
				}
				if res.exif == nil {
					return true, nil
				}
				// upsert exif row keyed by asset id
				var existing Exif
				if err := a.store.DB.Where("asset_id = ?", it.ID).First(&existing).Error; err != nil {
					res.exif.ID = newUUID()
					res.exif.AssetID = it.ID
					if cerr := a.store.DB.Create(res.exif).Error; cerr != nil {
						return false, cerr
					}
					a.store.DB.Model(&Asset{}).Where("id = ?", it.ID).Update("exif_id", res.exif.ID)
				} else {
					a.store.DB.Model(&Exif{}).Where("id = ?", existing.ID).Updates(map[string]any{
						"make":               res.exif.Make,
						"model":              res.exif.Model,
						"date_time_original": res.exif.DateTimeOriginal,
						"latitude":           res.exif.Latitude,
						"longitude":          res.exif.Longitude,
						"orientation":        res.exif.Orientation,
					})
				}
				return true, nil
			},
		},
		"videoConversion": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				var assets []Asset
				q := a.store.DB.Where("type = ? AND is_trash = ?", "VIDEO", false)
				if !force {
					q = q.Where("encoded_video_path = ?", "")
				}
				if err := q.Find(&assets).Error; err != nil {
					return nil, err
				}
				out := make([]jobItem, 0, len(assets))
				for _, x := range assets {
					out = append(out, jobItem{ID: x.ID, Path: x.OriginalPath, Type: "VIDEO"})
				}
				return out, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				raw, err := os.ReadFile(it.Path)
				if err != nil {
					return false, err
				}
				out, terr := a.video.Transcode(raw, video.TranscodeOptions{
					Format:     "mp4",
					VideoCodec: "h264",
					AudioCodec: "copy",
					Preset:     "software",
				})
				if terr != nil || len(out) == 0 {
					return false, terr
				}
				encDir := filepath.Join(a.cfg.ResourceDir, "encoded-video")
				_ = os.MkdirAll(encDir, 0o755)
				dst := filepath.Join(encDir, it.ID+".mp4")
				if werr := os.WriteFile(dst, out, 0o644); werr != nil {
					return false, werr
				}
				a.store.DB.Model(&Asset{}).Where("id = ?", it.ID).Updates(map[string]any{
					"encoded_video_path": dst,
					"updated_at":         time.Now().UTC(),
				})
				return true, nil
			},
		},
		"duplicateDetection": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				// compute duplicate groups by checksum; the result is queryable
				// via GET /api/assets/duplicates. The job itself just (re)scans.
				type dup struct {
					Checksum string
					Count    int
				}
				var dups []dup
				if err := a.store.DB.Model(&Asset{}).Select("checksum, count(*) as count").
					Where("is_trash = ?", false).Group("checksum").Having("count > 1").Scan(&dups).Error; err != nil {
					return nil, err
				}
				out := make([]jobItem, 0, len(dups))
				for i, d := range dups {
					out = append(out, jobItem{ID: d.Checksum, Path: "", Type: ""})
					_ = i
				}
				return out, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				// nothing to mutate per group; detection is query-driven.
				return true, nil
			},
		},
		// integrityCheck: official JobName. Runs a genuine filesystem audit
		// (missing/untracked/checksum mismatch counts) via runIntegrityScan.
		"integrityCheck": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				return []jobItem{{ID: "integrity"}}, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				_, err := a.runIntegrityScan()
				return err == nil, err
			},
		},
		// backupDatabase: consistent SQLite snapshot into
		// resources/backups/ (S4). Uses VACUUM INTO after a WAL checkpoint so
		// the copy is self-contained; keeps the newest N files.
		"backupDatabase": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				return []jobItem{{ID: "backup"}}, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				path, err := a.createDatabaseBackup()
				if err != nil {
					return false, err
				}
				log.Printf("[jobs] backupDatabase written: %s", path)
				return true, nil
			},
		},
		// Periodic trash-expiry cleanup (Immich's "userDeleteCheck" cron).
		// Supported: it permanently deletes assets older than trashDays.
		"trashCleanup": {
			supported: true,
			items: func(a *App, force bool) ([]jobItem, error) {
				return []jobItem{{ID: "trash"}}, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				_, err := a.runTrashCleanup()
				return err == nil, err
			},
		},
		"smartSearch": {
			supported: a.ml != nil && len(a.ml.Capabilities()) > 0,
			items: func(a *App, force bool) ([]jobItem, error) {
				var assets []Asset
				q := a.store.DB.Where("type = ? AND is_trash = ?", "IMAGE", false)
				if !force {
					q = q.Where("id NOT IN (SELECT asset_id FROM asset_mls)")
				}
				if err := q.Find(&assets).Error; err != nil {
					return nil, err
				}
				out := make([]jobItem, 0, len(assets))
				for _, asset := range assets {
					out = append(out, jobItem{ID: asset.ID, Path: asset.OriginalPath, Type: asset.Type})
				}
				return out, nil
			},
			run: func(a *App, it jobItem) (bool, error) {
				data, err := os.ReadFile(it.Path)
				if err != nil {
					return false, err
				}
				result, err := a.ml.Infer(ml.Request{Capability: ml.CapabilityImageDescription, Data: data, MIME: mimeByExt(it.Path), Name: filepath.Base(it.Path), Language: a.cfg.OCRLanguage})
				if err != nil {
					return false, err
				}
				labels, _ := json.Marshal(result.Labels)
				now := time.Now().UTC()
				return true, a.store.DB.Save(&AssetML{AssetID: it.ID, Description: result.Text, LabelsJSON: string(labels), CreatedAt: now, UpdatedAt: now}).Error
			},
		},
		// The following capabilities require separate ML adapters.
		"objectDetection":          {supported: false},
		"facialRecognition":        {supported: false},
		"storageTemplateMigration": {supported: false},
		"tagCopy":                  {supported: false},
		"tagImage":                 {supported: false},
	}
}

// jobWorkers bounds concurrent media processing across all jobs.
const jobWorkers = 4

// jobBatchSize bounds how many items one dispatch processes before the next
// chained batch (S3) takes over. Keeps SQLite write pressure bounded.
var jobBatchSize = 50

// handleJobCommand mirrors POST /api/jobs/:name. It accepts either a manual
// trigger (no body / {force:true}) or a QueueCommandDto{command} to
// pause/resume/empty/clear-failed the queue.
func (a *App) handleJobCommand(c *gin.Context) {
	id := c.Param("id")
	if _, ok := a.requireAdmin(c); !ok {
		return
	}
	var cmd struct {
		Command string `json:"command"`
		Force   bool   `json:"force"` // official JobCommandDto.force
	}
	_ = c.ShouldBindJSON(&cmd)
	if cmd.Command != "" {
		switch cmd.Command {
		case "pause":
			a.queuePaused.Store(id, true)
			c.JSON(http.StatusOK, gin.H{"jobId": id, "paused": true})
			return
		case "resume":
			a.queuePaused.Store(id, false)
			c.JSON(http.StatusOK, gin.H{"jobId": id, "paused": false})
			return
		case "empty", "clear-failed":
			if st, ok := a.jobStates.Load(id); ok {
				s := st.(*jobState)
				s.mu.Lock()
				if cmd.Command == "clear-failed" {
					s.failed = 0
				}
				s.completed = 0
				s.active = 0
				s.total = 0
				s.running = false
				s.lastError = ""
				s.mu.Unlock()
			}
			a.queuePaused.Store(id, false)
			c.JSON(http.StatusOK, gin.H{"jobId": id, "cleared": true})
			return
		case "start":
			// fall through to dispatch below; official JobCommandDto carries
			// {command, force} — force re-processes all assets this run.
			a.dispatchJob(c, id, cmd.Force)
			return
		default:
			c.JSON(http.StatusBadRequest, gin.H{"message": "unknown command: " + cmd.Command, "statusCode": 400})
			return
		}
	}
	a.dispatchJob(c, id, cmd.Force)
}

// dispatchJob starts (or force-starts) a job by id. Immich's JobCreateDto
// carries {force:true}: when set, the job re-processes ALL eligible assets
// instead of only the ones missing byproducts.
func (a *App) dispatchJob(c *gin.Context, id string, force bool) {
	reg := a.jobRegistry()
	spec, ok := reg[id]
	if !ok {
		c.JSON(http.StatusBadRequest, gin.H{"message": "unknown job: " + id, "statusCode": 400})
		return
	}
	if !spec.supported {
		c.JSON(http.StatusOK, gin.H{
			"jobId":       id,
			"started":     false,
			"unsupported": true,
			"message":     "job requires an ML/AI backend not bundled with immich-go; skipped",
		})
		return
	}

	st := a.jobStateFor(id)
	st.mu.Lock()
	alreadyRunning := st.running
	st.mu.Unlock()
	if alreadyRunning {
		c.JSON(http.StatusOK, gin.H{"jobId": id, "started": false, "alreadyRunning": true})
		return
	}

	if force {
		a.dispatchChainedForce(c, id, spec)
		return
	}

	items, err := spec.items(a, false)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": err.Error(), "statusCode": 500})
		return
	}
	if len(items) == 0 {
		st.begin(0)
		st.mu.Lock()
		st.running = false
		st.finishedAt = time.Now()
		st.mu.Unlock()
		c.JSON(http.StatusOK, gin.H{"jobId": id, "started": true, "total": 0, "message": "nothing to process"})
		return
	}

	st.begin(len(items))
	go a.runJob(id, spec, items)
	c.JSON(http.StatusOK, gin.H{"jobId": id, "started": true, "total": len(items)})
}

// dispatchChainedForce starts a full (force) rebuild that processes assets in
// chained batches: only the first batch is materialized now; each completed
// batch dispatches the next one until the cursor passes the snapshot upper
// bound. Epic §5.5: never one giant task, never a pre-materialized queue.
func (a *App) dispatchChainedForce(c *gin.Context, id string, spec jobSpec) bool {
	st := a.jobStateFor(id)

	var maxID string
	if err := a.store.DB.Model(&Asset{}).Select("COALESCE(MAX(id),'') AS id").Scan(&maxID).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"message": err.Error(), "statusCode": 500})
		return false
	}
	ch := &jobChain{idUpper: maxID + "\uffff", force: true}
	jobChains.Store(id, ch)

	st.mu.Lock()
	st.forceChain = true
	st.mu.Unlock()

	a.dispatchNextForceBatch(id, spec, ch)

	st.mu.Lock()
	running := st.running
	st.mu.Unlock()
	c.JSON(http.StatusOK, gin.H{
		"jobId": id, "started": true, "mode": "chained-force",
		"batchSize": jobBatchSize, "running": running,
	})
	return true
}

// dispatchNextForceBatch materializes and runs ONE batch; on completion it
// schedules the next batch unless paused or exhausted.
func (a *App) dispatchNextForceBatch(id string, spec jobSpec, ch *jobChain) {
	ch.mu.Lock()
	start := ch.nextStart
	force := ch.force
	idUpper := ch.idUpper
	ch.mu.Unlock()
	_ = start
	_ = force
	_ = idUpper

	items, err := spec.itemsForceBatch(a, idUpper, &ch.mu, &ch.nextStart)
	if err != nil {
		log.Printf("[jobs] %s force batch error: %v", id, err)
		a.finishJobState(id)
		return
	}
	if len(items) == 0 {
		log.Printf("[jobs] %s chained force complete", id)
		a.finishJobState(id)
		jobChains.Delete(id)
		return
	}

	st := a.jobStateFor(id)
	if st.total == 0 {
		// First batch: initialize totals with a growing estimate.
		st.begin(jobBatchSize)
	} else {
		st.mu.Lock()
		st.total += len(items)
		st.mu.Unlock()
	}
	go func() {
		a.runJob(id, spec, items)
		// Chain: schedule next batch unless queue is paused.
		if paused, ok := a.queuePaused.Load(id); ok && paused.(bool) {
			log.Printf("[jobs] %s chain paused before next batch", id)
			return
		}
		a.dispatchNextForceBatch(id, spec, ch)
	}()
}

// finishJobState marks a job finished.
func (a *App) finishJobState(id string) {
	st := a.jobStateFor(id)
	st.mu.Lock()
	st.running = false
	st.finishedAt = time.Now()
	st.mu.Unlock()
}

// jobChain tracks a force (full-rebuild) run: the id upper bound snapshot at
// trigger time bounds the set, and nextStart is the cursor for the chained
// batch. Only ONE pending batch exists at any time (Epic §5.5 decision).
type jobChain struct {
	mu        sync.Mutex
	idUpper   string // lexicographic exclusive upper bound on asset ids
	nextStart int    // count of eligible items already dispatched
	force     bool
}

var jobChains sync.Map // map[jobID]*jobChain

// runJob executes the items with a bounded worker pool, updating progress.
// Items are processed in chunks of jobBatchSize; between chunks the queue
// pause flag is honored so admins can stop long-running jobs promptly.
func (a *App) runJob(id string, spec jobSpec, items []jobItem) {
	st := a.jobStateFor(id)
	for start := 0; start < len(items); start += jobBatchSize {
		if paused, ok := a.queuePaused.Load(id); ok && paused.(bool) {
			log.Printf("[jobs] %s paused at item %d/%d", id, start, len(items))
			st.mu.Lock()
			st.running = false
			st.finishedAt = time.Now()
			st.mu.Unlock()
			return
		}
		end := start + jobBatchSize
		if end > len(items) {
			end = len(items)
		}
		a.runBatch(id, spec, items[start:end])
	}
	log.Printf("[jobs] %s finished: %d processed", id, len(items))
}

// runBatch processes one chunk of items concurrently.
func (a *App) runBatch(id string, spec jobSpec, batch []jobItem) {
	st := a.jobStateFor(id)
	sem := make(chan struct{}, jobWorkers)
	var wg sync.WaitGroup
	for _, it := range batch {
		wg.Add(1)
		sem <- struct{}{}
		go func(it jobItem) {
			defer wg.Done()
			defer func() { <-sem }()
			var ok bool
			var err error
			for attempt := 1; attempt <= 3; attempt++ {
				ok, err = spec.run(a, it)
				if ok || err == nil {
					break
				}
				if attempt < 3 {
					time.Sleep(time.Duration(attempt) * 250 * time.Millisecond)
				}
			}
			st.tick(ok, err)
		}(it)
	}
	wg.Wait()
}

// handleJobStatus returns live progress for a job id.
func (a *App) handleJobStatus(c *gin.Context) {
	id := c.Param("id")
	st, ok := a.jobStates.Load(id)
	if !ok {
		c.JSON(http.StatusOK, gin.H{"jobId": id, "active": 0, "completed": 0, "total": 0, "running": false})
		return
	}
	c.JSON(http.StatusOK, st.(*jobState).snapshot())
}

// handleJobsList mirrors GET /api/jobs (legacy QueuesResponseLegacyDto): one
// block per named queue, each carrying {jobCounts, queueStatus:{isActive,
// isPaused}}. The maintenance page polls this endpoint every 2s and reads
// `integrityCheck.queueStatus.isActive` — the flat shape broke it.
func (a *App) handleJobsList(c *gin.Context) {
	out := gin.H{}
	for _, name := range queueNames {
		paused := false
		if v, ok := a.queuePaused.Load(name); ok {
			paused = v.(bool)
		}
		out[name] = gin.H{
			"jobCounts":   a.queueStats(name),
			"queueStatus": gin.H{"isActive": a.queueRunning(name), "isPaused": paused},
		}
	}
	c.JSON(http.StatusOK, out)
}

// handleJobCreate mirrors POST /api/jobs (createJob). Triggers a manual job by
// name (JobCreateDto{name, force}). It reuses the same dispatcher as /jobs/:id.
func (a *App) handleJobCreate(c *gin.Context) {
	if _, ok := a.requireAdmin(c); !ok {
		return
	}
	var body struct {
		Name  string `json:"name"`
		Force bool   `json:"force"` // official JobCreateDto.force
	}
	if err := c.ShouldBindJSON(&body); err != nil || body.Name == "" {
		c.JSON(http.StatusBadRequest, gin.H{"message": "job name required", "statusCode": 400})
		return
	}
	a.dispatchJob(c, body.Name, body.Force)
}

// itemsForceBatch returns the next force-mode batch for a chained run. It
// selects up to jobBatchSize assets (id > lastID, id < idUpper, ordered by id)
// and advances *cursor by the number returned. The mutex guards the cursor
// across chained goroutines.
func (spec jobSpec) itemsForceBatch(a *App, idUpper string, mu *sync.Mutex, cursor *int) ([]jobItem, error) {
	mu.Lock()
	// Offset-cursor over the id-ordered eligible set, bounded per batch. The
	// idUpper snapshot bound excludes assets created after the force trigger
	// (they follow the normal pipeline and need no rebuild).
	var assets []Asset
	q := a.store.DB.Where("id < ?", idUpper).Order("id").Offset(*cursor).Limit(jobBatchSize)
	if err := q.Find(&assets).Error; err != nil {
		mu.Unlock()
		return nil, err
	}
	out := make([]jobItem, 0, len(assets))
	for _, as := range assets {
		out = append(out, jobItem{ID: as.ID, Path: as.OriginalPath, Type: as.Type})
	}
	*cursor += len(out)
	mu.Unlock()
	return out, nil
}

// ensure jobStateFor returns (creating if needed) the per-job state.
func (a *App) jobStateFor(id string) *jobState {
	st, _ := a.jobStates.LoadOrStore(id, &jobState{})
	return st.(*jobState)
}

// unused helper kept to avoid import churn if json is needed for debugging.
var _ = json.Marshal

// handleAssetJobs mirrors POST /api/assets/jobs (runAssetJobs). Re-runs a job
// (thumbnailGeneration / metadataExtraction / videoConversion / duplicateDetection
// / ocr) for the explicitly listed asset IDs. This is genuine per-asset
// re-processing, not a stub.
func (a *App) handleAssetJobs(c *gin.Context) {
	if _, ok := a.requireAdmin(c); !ok {
		return
	}
	var body struct {
		AssetIDs []string `json:"assetIds"`
		Name     string   `json:"name"`
	}
	if err := c.ShouldBindJSON(&body); err != nil || len(body.AssetIDs) == 0 || body.Name == "" {
		c.JSON(http.StatusBadRequest, gin.H{"message": "assetIds and name required", "statusCode": 400})
		return
	}

	// Map the asset job name onto the supported registry job.
	regName := body.Name
	switch body.Name {
	case "thumbnailGeneration", "metadataExtraction", "videoConversion", "duplicateDetection", "ocr":
		regName = body.Name
	default:
		c.JSON(http.StatusBadRequest, gin.H{"message": "unsupported asset job: " + body.Name, "statusCode": 400})
		return
	}
	reg := a.jobRegistry()
	spec, ok := reg[regName]
	if !ok || !spec.supported {
		c.JSON(http.StatusOK, gin.H{"jobName": body.Name, "started": false, "unsupported": true, "count": 0})
		return
	}

	// Build job items only for the requested, still-existing assets.
	var items []jobItem
	for _, id := range body.AssetIDs {
		var as Asset
		if err := a.store.DB.First(&as, "id = ?", id).Error; err != nil {
			continue
		}
		items = append(items, jobItem{ID: as.ID, Path: as.OriginalPath, Type: as.Type})
	}
	if len(items) == 0 {
		c.JSON(http.StatusOK, gin.H{"jobName": body.Name, "started": true, "count": 0})
		return
	}

	st := a.jobStateFor("asset:" + body.Name)
	st.begin(len(items))
	go a.runJob("asset:"+body.Name, spec, items)
	c.JSON(http.StatusOK, gin.H{"jobName": body.Name, "started": true, "count": len(items)})
}
